### ISSUE TITLE
Darkling Woods Glitching Map Sprites?

### ISSUE THREAD

**Issue by SdeSpencer** [lushen124/Universal-FE-Randomizer#110] opened 2019-04-15 13:54 UTC
I don’t know if this is a fixed issue (game was randomized around 0.7.3) or even was caused by the emulator or something, but Darkling Woods got very visibly glitchy in one run I’ve seen (https://www.twitch.tv/videos/411252694 , first Map)

**Comment by lushen124** [comment] 2019-04-18 03:07
I wonder if there's a limit to how many sprites can be on a map, since it looks like the summon was when things started to get weird (or I screwed something up with the summons). Chapter 20 does have a very large number of enemies I don't recall doing anything about map sprites, but since it was randomized using 0.7.3, it might also just be general bugginess. I'd be interested to know if it still happens on 0.8.x.

**Comment by lushen124** [comment] 2020-02-28 06:08
Closing this until we have more info on what might be causing this or specific steps to reproduce.

**Closed by lushen124** 2020-02-28 06:08 UTC
Labels: FE8
