### ISSUE TITLE
Nothing randomizes into Mage (M)

### ISSUE THREAD

**Issue by Rmccallu** [lushen124/Universal-FE-Randomizer#171] opened 2019-05-20 23:21 UTC
I've randomized Sacred Stones a bunch of times, and one thing I always found odd was how common Pupil was. I've gotten roughly 10 pupils throughout the course of all my different runs, and maps would have them as the only mages, but a "real" mage appeared once in a blue moon, and I think I've found the reason for it. After opening up the changelog after I'd given up on my current seed and was about to delete it, I found really unusual things. First, Mage (F) seems to be one of the rarest classes, only beaten by Manakete. Second, after using ctrl f and going through all the classes that enemies were turned into, there was not a single enemy that was turned into a male mage. The other 2 "recruits" were roughly as common as any other class, even though it feels like I've only ever gotten journeymen and no fighters.  Priests and Clerics also have the same problem as Mage, though they still seem to be problematic (their inventory aren't being randomized).

Also, manakete isn't in the category for "safe for fliers to become", even though (in FE8 only) it is safe. Only bosses seem to have dragonstones, so I wouldn't mind seeing them a bit more as flying bosses. Heck, having Valter as one would be really fun. I've only ever had 1 manakete boss ever, and it was really challenging and fun. Granted, it was past the mid-point, and I could see the Ch 2 boss getting +15 defenses being unfair.

**Comment by lushen124** [comment] 2019-05-28 04:03
Based on the code as far as I can tell, Mage and Mage_F aren't treated any different from the other classes. Do you remember what settings you were using? That might help me narrow down what might be causing the issue, though I can't reproduce the issue myself (I seem to be getting some mages here and there)

The only thing I can think of is FE8 has a smaller cast to begin with, but if you're seeing the same pattern in minion randomization, then it sounds like something is up.

As for manaketes, I actually removed that class from the valid classes set, mostly because the palette data was wonky, but I might take another crack at it since I rewrote the palette logic to be more complete. You don't have to worry about early manaketes because the randomizer actually considers them as a promoted class, so they'll only start showing up potentially with Tirado (which might be a bit too early, but it's at least given you some time to get your team together).

**Comment by lushen124** [comment] 2020-10-03 01:42
Closing for the time being, as this issue might be resolved with #298

**Closed by lushen124** 2020-10-03 01:42 UTC
Labels: FE8, enhancement
