### ISSUE TITLE
[FE9] Can't get past B rank weapons?

### ISSUE THREAD

**Issue by Yetimain** [lushen124/Universal-FE-Randomizer#304] opened 2020-10-12 22:08 UTC
I randomized a path of radiance file and thought it was taking to long to get weapon ranks up. I decided to hack in some arm scrolls to check and none of my units are able to promote their weapon skills past B. (this will make fighting the black knight impossible) I know that un-promoted classes are locked to B rank weapons but my units have already promoted to 2nd tier. (Ike's a halbider Oscar a beserker, etc). Is it possible that the randomizer accidentally codded in that all promotes should be treated as un-promoted? if thats the case is there anything to do about it?

**Comment by lushen124** [comment] 2020-10-18 18:33
That shouldn't be the case, but I can look into it. I think normally, promoted classes should have SID_HIGHER that unlocks the weapon ranks to S, so unless that skill was somehow removed at some point, I'm not quite sure. Is this across all characters/all classes? or is it only an issue with specific combinations?

**Comment by Yetimain** [comment] 2020-10-18 21:36
It may have just glitched that it took the SID_HIGHER away from everyone that was randomized? No one on my team can get past B I checked all of my units, however enemy units have S rank weapon levels. Would it be possible to just apply an AR code that gives everyone in my army the SID_HIGHER skill?

**Comment by lushen124** [comment] 2020-10-20 00:16
What settings did you use? I can see if I can reproduce the issue you have. Right now, it's just a guess as to what the issue is. It's weird that you're missing SID_HIGHER, because I don't touch that skill.

**Comment by lushen124** [comment] 2021-05-28 19:55
Closing for the time being, until we get more info on whether this is reproducible and how to reproduce it.

**Closed by lushen124** 2021-05-28 19:55 UTC
Labels: FE9, bug
