### ISSUE TITLE
[FE8] Growth Rates aren't very random

### ISSUE THREAD

**Issue by smbai-smrpg** [lushen124/Universal-FE-Randomizer#384] opened 2021-12-16 12:35 UTC
I dunno whats going on, but I have made like 30 seeds with various different settings, and the growth rates of Characters don't change, or hardly change at all. And in EVERY single seed, EVERY class growth is increased by 15% from vanilla. No more, no less. I have no clue why. It was my understanding that if you randomize growth rates and use the full random setting, that your growths will all change to the min/max you set. In my case I had 15% - 255%, but growths never randomized at all. What the heck am I doing wrong?

**Comment by PurdraDan** [comment] 2021-12-16 12:39
Which settings are you using? are you using CON or Affinity randomization?

**Comment by smbai-smrpg** [comment] 2021-12-17 01:35
https://gyazo.com/bb4ac2a9c8d02ada6ea58a3b96c2004c

**Comment by smbai-smrpg** [comment] 2021-12-17 01:40
I took out randomize con, affinity, and recruitment and it seemed to fix it. Now everyone has wild growths between 15 and 255

**Comment by PurdraDan** [comment] 2021-12-17 10:10
Yeah con and affinity seem to be causing the problem, see #356

**Comment by lushen124** [comment] 2023-04-03 01:45
Closing as a duplicate of #356, which has a fix incoming.

**Closed by lushen124** 2023-04-03 01:45 UTC
