### ISSUE TITLE
How long is a FE9 Randomiziation supposed to take?

### ISSUE THREAD

**Issue by DarkScent9** [lushen124/Universal-FE-Randomizer#199] opened 2020-02-27 17:53 UTC
I have been waiting for an hour to randomize...

I have an US FE9 Rom, as it should be.

It gets stuck at randomizing classes.

Are there any options I am supposed not to touch? Is there a minimum specs for using this program?

I have all options enabled except cross race and cross gender classes.

Class replacement at 100%.
Skill chance at 100%

Am I missing something?

**Comment by lushen124** [comment] 2020-02-28 03:46
It shouldn't take more than 2 minutes or so. I did find a bug with herons trying to be assigned weapons, so if you're including special classes, disable that for the time being. I'll work on a fix for this.

**Comment by DarkScent9** [comment] 2020-02-28 12:06
Don't know if the Confirmation helps you any, but by disabling special classes I got through the Class randomization process.

However, It then Hanged on Growth randomization. The cause for that one is adjusting HP Growth, I believe, because when I disabled that option I got past it. (Used together with absolute randomization 15-80, for your information).

And now it hangs at Buffing enemies ^^' I'll give it an Hour to terminate (As it currently cycles through every enemy in the game and tries to give it a skill, maybe failing and then retrying? I don't know your algorithm). I am hazarding a guess and would make Skills for Enemies and bosses at 100% responsible.

**Comment by lushen124** [comment] 2020-02-28 15:50
It shouldn't take anywhere near that long. The class randomization is an issue I've reproduced and have a fix for, and I've heard reports of the Growth randomization also causing issues with some settings (and also have a fix for), but I've never heard of buffing enemies to also take a long time. What settings are you using? Cycling through every enemy would take a long time by hand, but for a computer, this shouldn't take more than a couple seconds at most, and that's probably on a computer that's not even capable of running Dolphin.

That fix also makes it so that any issues are actually raised and communicated to the user instead of failing silently. With that, it'll make it far easier to debug, because we'll at least know why it's failing.

Are you on Windows? I can give you a quick updated build to see if this sheds more light on things.

**Comment by lushen124** [comment] 2020-02-28 16:03
Actually, I see the issue now. There's an issue with ease-in/ease-out boss scaling.

If you are on Windows, here's an updated build that addresses all three of the issues you've found and hopefully gives us more clues as to why anything else might be failing. If you're on something else, let me know, and I can make a special build for those.

[Yune.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/4267906/Yune.zip)

**Comment by DarkScent9** [comment] 2020-02-28 18:29
This build it seems to work!

Before, on the other build, I also tried to see which setting in particular for buffing enemies failed on me, and as far as I could tell it was none of them. I disabled all of them and it still got stuck at Buffing enemies. Though, if it helps, for buffing bosses, it was disabled, but set to ease in/ease out and I could imagine it to be still the culprit.

Now it works with all the settings, including "emphasize HP Growth", "Special classes" and whatever caused the buffing enemies hang. 

For full disclosure, here are my settings:

It is cut off at the bottom, but the settings for all skills are equal.

![Settings](https://user-images.githubusercontent.com/61361335/75575703-4f2e0e00-5a60-11ea-8d3a-01778c82ced1.PNG)

**Closed** 2020-03-17 04:16 UTC
Labels: FE9, bug
