### ISSUE TITLE
FE8 not saving

### ISSUE THREAD

**Issue by TWACC** [lushen124/Universal-FE-Randomizer#192] opened 2020-01-01 11:21 UTC
FE8 won't save. The 'no data' on the save screen just stays the same when I try to save. I don't know if this is an issue with Yune or the rom or something else.

**Comment by lushen124** [comment] 2020-01-01 14:26
Hmm... the randomizer doesn't handle save files. This is usually a setting on your emulator. Saving should result in a .sav file appearing in wherever the save folder your emulator specifies. What emulator are you using?

**Comment by TWACC** [comment] 2020-01-01 15:44
I think it was the rom. I tried another FE8 rom and it worked fine.

**Comment by lushen124** [comment] 2020-01-02 14:06
Weird. Can you send me an IPS or UPS patch file for the randomized ROM and the platform/emulator that you're using? It doesn't have any issues saving on my side when randomizing classes, recruitment, and growths using VisualBoyAdvance on Windows.

**Comment by TWACC** [comment] 2020-01-02 16:02
Sorry, I'm a little technologically illiterate. What is that and how do I do that? I don't have the rom anymore so if that's needed there may be trouble. As for platform and emulator, I play on my android phone using an emulator called PlayGBAGBC. Sorry again for not being more helpful, like I said before I'm not very good with these sorts of things.

**Comment by lushen124** [comment] 2020-01-03 16:35
No worries.

If you don't have the ROM, can you reproduce it with another randomized one? If it's an issue with the randomizer, most results should have the same issue. Alternatively, if you remember the seed phrase you used (or if you saved the changelog), using the same seed should result in the same randomized ROM. Once you have the bugged ROM, then you can use something like LunarIPS or NUPS to create a patch file. Let me know if you need help with creating the patch.

I also recommend trying the same (bugged) ROM with a different emulator. If it works there, then that'll narrow down what could be wrong. If you can try VisualBoyAdvance, that would be the best, but most PC emulators seem to have no issues in my experience and RetroArch for Mac and Linux seem to work fine as well.

The emulator you listed, I've never used before. Are you able to try other GBA emulators on Android?

**Comment by TWACC** [comment] 2020-01-03 18:59
Actually it turns out I do have the rom still. I only deleted it from my phone. I still have a copy on my computer. Later today I'll test the rom on VBA and then I'll try to create a patch file to send you. Also I did save the changelog and used the same phrase when I randomized that other rom that worked.

**Comment by TWACC** [comment] 2020-01-03 19:54
It seems to work fine on VBA. Weird. Maybe something went wrong when I moved it from my computer to my phone? I don't know if you still need that patch but I'm not quite sure how to create it. I got NUPS but the instructions in the readme don't make sense to me.

**Comment by lushen124** [comment] 2020-02-17 07:10
Closing this issue for the time being. I'm not entirely convinced this is because of the ROM and not the emulator, but I'll keep it in mind if I find any other leads/repro steps.

**Closed by lushen124** 2020-02-17 07:10 UTC
