### ISSUE TITLE
No Affinity = Massive boost???

### ISSUE THREAD

**Issue by bobosmith01** [lushen124/Universal-FE-Randomizer#197] opened 2020-02-25 11:54 UTC
Hi! I'm playing a randomized FE7! I noticed some glitchy icons in the support menu, and noticed that, hey! Some units don't have affinities. That's cool, I'm down.

So I got Pent and Louise, and wham. Pent doesn't have an affinity. But, when I placed the two close to one another...

Well, the boost was far from small. Is this intended? I can't imagine it being so... I haven't tested the other affinity-less supports, but if they do work fine, perhaps it's the result of it specifically being Pent and Louise?

![image](https://user-images.githubusercontent.com/50797792/75245296-756f5780-579b-11ea-8d6c-bd7f62964240.png)

Here's the HTML document.

[random.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/4249828/random.zip)

**Comment by bobosmith01** [comment] 2020-02-25 11:56
Oh, turns out this was an issue from a while ago, too, with "Matthew losing his affinity" from a different user.

**Comment by bobosmith01** [comment] 2020-02-25 11:58
Ah! I should note, one of the mages in Chapter 4 (Lyn's mode, Occupation's Shadow, the Dorcas chapter), on Hard Mode, had "--" magic. Usually, most enemies had 0 magic as should be correct (thankfully, none of my units had the "--" magic!)

Unless this was fixed, resetting and resuming mid-chapter causes their magic to skyrocket, does it not?

**Comment by lushen124** [comment] 2020-02-28 03:51
-- usually means they somehow had negative stats. The problem is that when this gets saved and loaded, the negative becomes positive, due to how negative numbers are stored in binary and how the game processes them.

The randomizer does its best to set stats appropriately for minions, but some of the minions are actually defined specially as minion characters with negative stat offsets (presumably to make it easier than they would be otherwise). I don't take this into account today, so it can cause -- stats if applied to the wrong class bases. This most often happens with low level enemies, as higher level enemies will have enough additional stats to avoid a negative stat.

**Comment by lushen124** [comment] 2020-03-07 20:04
Closing this in favor of #167 to track the no affinity issue. The -- stat issue is tracked by #196 when it affects playable characters due to overflowing.

**Closed by lushen124** 2020-03-07 20:04 UTC
Labels: FE7, bug
