### ISSUE TITLE
Recruitment and growths randomization

### ISSUE THREAD

**Issue by simonjamesroger** [lushen124/Universal-FE-Randomizer#386] opened 2022-01-01 17:33 UTC
In Version 0.9.3, when you randomize recruitment, it does not randomize growths at all. It worked in previous versions, so it would be good to mention in documentation whether that's intentional or a bug.

**Comment by PurdraDan** [comment] 2022-01-01 18:11
That is by accident and I think is probably gonna be fixed in 1.0.0. see #356

**Comment by lushen124** [comment] 2023-04-03 01:45
Closing as a duplicate of #356, which has a fix incoming.

**Closed by lushen124** 2023-04-03 01:45 UTC
